/** @jsxImportSource @emotion/react */
import type { NextPage } from "next";
import Head from "next/head";
import { css, useTheme } from "@emotion/react";

const Home: NextPage = () => {
  const theme = useTheme();

  const title = (theme: any) =>
    css`
      color: ${theme.color.gray300};
    `;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 css={title(theme)}>Hi Jihyoun</h1>
    </div>
  );
};

export default Home;
